//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контакты
    {
        public int ID_Контакта { get; set; }
        public string ICQ { get; set; }
        public string E_mail { get; set; }
        public string Skype { get; set; }
        public Nullable<int> Клиент { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
