//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещения
    {
        public int ID_посетителя { get; set; }
        public Nullable<int> клиент { get; set; }
        public int услуга { get; set; }
        public Nullable<int> сотрудник { get; set; }
        public string дата { get; set; }
        public string время { get; set; }
        public string услуга_оказана { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
